### ISSUE TITLE
how did you solve the problem SyntaxError: invalid syntax in klipper?

### ISSUE THREAD

**Issue by songyx** [Ramalama2/Libreelec-RR-Scripts#1]
I got the same problem.
klipper@aml2:~$ python3 /home/klipper/klipper_config/printer.cfg -l /home/klipper/klipper_logs/klippy.log
  File "/home/klipper/klipper_config/printer.cfg", line 17
    enable_pin: !PD6
                ^
SyntaxError: invalid syntax
.
using armbian on a phnicomm n1 tvbox.
python3.7.3
thanks a lot.

**Comment by songyx** [comment]
ok,I solved the problem.I using kiauh install klipper.and it change the /etc/systemd/system/klipper.service to wrong:
"/home/klipper/klippy-env/bin/python /home/klipper/klipper_config/printer.cfg -l /home/klipper/klipper_logs/klippy.log"
right one is here:
"/home/klipper/klippy-env/bin/python /home/klipper/klipper/klippy/klippy.py /home/klipper/klipper_config/printer.cfg -l /home/klipper/klipper_logs/klippy.log"

tks anyway.

**Comment by Ramalama2** [comment]
Lol broh, libreelec has not much todo with klipper 😂
